### ISSUE TITLE
Crash python when parse Apple signed files

### ISSUE THREAD

**Issue by Proteas** [aaronst/macholibre#1]
Commands:
`from macholibre import macholibre
print macholibre.processFile('/bin/ls')`

Line:
`parser.py", line 329, in parseCerts`

Call Stack:
` thread 1: libcrypto.dylib`CMS_get0_type + 4, stop reason = EXC_BAD_ACCESS (code=1, address=0x367740)
 frame 0: 0x000000010410c5f7 libcrypto.dylib`CMS_get0_type + 4
 frame 1: 0x0000000101f2e427 _ctypes.so`ffi_call_unix64 + 79
 frame 2: 0x0000000101f2f2df _ctypes.so`ffi_call + 575
 frame 3: 0x0000000101f293ef _ctypes.so`_ctypes_callproc + 895
 frame 4: 0x0000000101f212df _ctypes.so`PyCFuncPtr_call + 303`

[ls-macOS.zip](https://github.com/aaronst/macholibre/files/322314/ls-macOS.zip)

**Comment by aaronst** [comment]
Hi Proteas,

First, thanks for checking out macholibre, I'm glad people are using it.  It looks like this might be a problem with openssl, what version are you using?

**Comment by Proteas** [comment]
I tested with openssl 1.0.2h_1 and 1.0.1m.

**Comment by aaronst** [comment]
Yeah... this sucks.  I've been using openssl 1.0.2g-fips on ubuntu 16.04 with no problems.  Looking at it a bit more, I think it might be ctypes not playing nice with the osx version of openssl.  I'm going to continue working on this, but I may need to switch from ctypescrypto to something else.  Sorry for the trouble, hopefully I'll have a solution by the end of the week.

**Comment by Proteas** [comment]
On Ubuntu, it can parse the 'ls', right ?
thank you very much for sharing the library. 
Maybe I will do more analysis this weekend.

**Comment by aaronst** [comment]
Correct, I've never had any troubles on Ubuntu.  I'm currently working with the author of ctypescrypto to get the OS X compatibility issues sorted out, we're making good progress.  Thanks for using it!  Let me know how I can make it better 😄

**Comment by aaronst** [comment]
@Proteas, I think we're good to go.

Make sure your openssl is up to date with brew.  Should be 1.0.2h.
```
brew update
brew install openssl
brew link --force openssl
openssl version
```

Update ctypescrypto to the latest version from github.  May require sudo.
```
pip uninstall ctypescrypto
pip install git+https://github.com/vbwagner/ctypescrypto.git
```

I was able to parse `/bin/ls` on my El Capitan machine, so I'm going to close this issue now.  If you have any more problems let me know.

**Comment by Proteas** [comment]
thank you. 👍
