### ISSUE TITLE
OutOfMemory crash

### ISSUE THREAD

**Issue by rammy22** [aaronst/macholibre#17]
Extracting data from `104166ae77e366f0b5d66ce09ae7c28f12914b7156cc5c00afd000b624b8a2f1` results in python process consuming all available memory on the system then crashing.

**Comment by aaronst** [comment]
@rammy22 Sorry for the delay, I've been on vacation for the past month.  Going to look at all these issues asap, thanks for reporting.

**Comment by aaronst** [comment]
@rammy22 I think this file is actually an old school Mach file.  The CPUTYPE is NS32332, which is a microprocessor from the 80's.  I think what I need to do is be more strict about the CPUTYPE's that I try to accept, this should be one that I reject.
