### ISSUE TITLE
Use module ´argparse` for option handling

### ISSUE THREAD

**Issue by htgoebel** [aaronst/macholibre#4]
The Readme says:

> For single files, make sure you put the filename first, before any options.

Please use `argparse` and overcome this limitation.

In the same turn you could remove the very, very unusual handling of globs, wich is normaly revolded by the shell already.

**Comment by aaronst** [comment]
@htgoebel thanks for taking the time to provide feedback on `macholibre`.

I'll definitely look at implementing this.  I'm curious though, is there any particular reason you're using it as a script vs a module?  If I can better understand your use case I might be able to make better changes.

**Comment by htgoebel** [comment]
> is there any particular reason you're using it as a script vs a module?

Simply because
a) I just wanted a small command line tool for "dumping" some mach-o files, and
b) the readme says it can be used [as a script](https://github.com/aaronst/macholibre#as-a-script).

**Comment by aaronst** [comment]
Okay, I've switched over to using `argparse`.  Take a look at the new `README.md`, try it out, and let me know.

**Comment by htgoebel** [comment]
It uses argparse now, but still `input` is a glob, which is *very* unusual (except if you are on Windows). Have a look at the [first example of arparse](https://docs.python.org/3.4/library/argparse.html#example), which allows passing an arbitrary number of `N`s.

**Comment by aaronst** [comment]
Ah yes I see, fixed.
