### ISSUE TITLE
Execution hangs on sample

### ISSUE THREAD

**Issue by rammy22** [aaronst/macholibre#6]
Attempting to extract the data, using standalone form, from 05575fb9fd4cbf35e53e80c3c9ccbc4f53d47c44b3e69e06b85bbfacb3669e1c results in a hang.

**Comment by aaronst** [comment]
Thanks @rammy22, I'll take a look.

**Comment by aaronst** [comment]
This is now fixed with the latest commit.  I was not checking for EOF when trying to read strings.  Thanks for the feedback!
