### ISSUE TITLE
AttributeError in parse_lcs()

### ISSUE THREAD

**Issue by rammy22** [aaronst/macholibre#8]
``` python
Could not parse file: /sample/1e733b7b44454690a84d33b715b16ccf1a8f2312abb8ccd260edf88736198730
ERROR:root:Traceback (most recent call last):
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/__init__.py", line 67, in main
    parse(args.input[0], f=args.output)
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/__init__.py", line 41, in parse
    p.parse_file()
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/parser.py", line 814, in parse_file
    endi=identity[1], size=self.get_file_size()))
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/parser.py", line 746, in parse_macho
    lc.parse_lcs()
  File "/.virtualenvs/tmp-6c7055859c255549/lib/python2.7/site-packages/macholibre/loadcommander.py", line 529, in parse_lcs
    self.addAbnormality(a)
AttributeError: 'LoadCommander' object has no attribute 'addAbnormality'
```

**Comment by aaronst** [comment]
This mach-o is bizarre.  It looks like it's been mangled in a few spots.  Namely:

* The 4 byte command field at offset 3032 is 0x5F070000, when in fact it should actually be 0x0B000000 (DYSYMTAB).  I can tell this by the following 4 bytes (size field) and the previous load command being SYMTAB.
* The 4 byte command field and subsequent size field at offset 3368 are 0x0E0C0000 and 0x4F040000, respectively.  They should actually be 0x0C000000 and 0x38000000, for a LOAD_DYLIB command with size 56.  I can tell this by the following fields in the load command, namely the path string for a dylib.
* The 4 byte command field at offset 3520 is 0xF4080000 but should again be 0x0C000000 for the same reason as above.
* The 4 byte command field and subsequent size field at offset 4328 are 0x5D070000 and 0xA50B0000, respectively.  They should actually be 0x0C000000 and 0x58000000 for a LOAD_DYLIB command with size 88.
* The 4 byte command field at offset 4528 is 0xC1040000 but should again be 0x0C000000.

If we make the necessary patches, it is then able to partially parse, but it seems there are a few other places where the data is borked (SYMTAB fields, and code signature magics). I wonder, if this is malware of some sort, if there is intended to be a prior stage that patches this file before running.  Either way, macholibre is not at fault here.

**Comment by aaronst** [comment]
Added checks that handles this case.
